program FPTest2019;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  Forms,
  Vcl.Themes,
  Vcl.Styles,
  Interfaces.Enums in '..\Common\Interfaces\Interfaces.Enums.pas',
  Interfaces.GUIRecords in 'Interfaces\Interfaces.GUIRecords.pas',
  Interfaces.Model.Pattern.Observer in '..\Common\Interfaces\Models\Interfaces.Model.Pattern.Observer.pas',
  Interfaces.Model.Notification in '..\Common\Interfaces\Models\Interfaces.Model.Notification.pas',
  Interfaces.Model.Classes.Sales in 'Interfaces\Models\Interfaces.Model.Classes.Sales.pas',
  Interfaces.Model.Classes.Sale in 'Interfaces\Models\Interfaces.Model.Classes.Sale.pas',
  Interfaces.Model.Classes.Sale.Details in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Details.pas',
  Interfaces.Model.Classes.Sale.Detail in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Detail.pas',
  Interfaces.Model.Classes.Sale.Cancellations in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Cancellations.pas',
  Interfaces.Model.Classes.Sale.Cancellation in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Cancellation.pas',
  Interfaces.Model.Classes.Sale.Payments in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Payments.pas',
  Interfaces.Model.Classes.Sale.Payment in 'Interfaces\Models\Interfaces.Model.Classes.Sale.Payment.pas',
  Interfaces.Model.Classes.Client in 'Interfaces\Models\Interfaces.Model.Classes.Client.pas',
  Interfaces.Model.Main in 'Interfaces\Models\Interfaces.Model.Main.pas',
  Interfaces.Model.Sale in 'Interfaces\Models\Interfaces.Model.Sale.pas',
  Interfaces.Model.Reversal in 'Interfaces\Models\Interfaces.Model.Reversal.pas',
  Interfaces.Model.CashInOut in 'Interfaces\Models\Interfaces.Model.CashInOut.pas',
  Interfaces.Model.Reports in 'Interfaces\Models\Interfaces.Model.Reports.pas',
  Interfaces.Model.Login in 'Interfaces\Models\Interfaces.Model.Login.pas',
  Interfaces.Model.SelectItem in 'Interfaces\Models\Interfaces.Model.SelectItem.pas',
  Interfaces.Model.SelectClient in 'Interfaces\Models\Interfaces.Model.SelectClient.pas',
  Interfaces.Model.CheckItem in 'Interfaces\Models\Interfaces.Model.CheckItem.pas',
  Interfaces.Model.SelectSale in 'Interfaces\Models\Interfaces.Model.SelectSale.pas',
  Interfaces.ViewModel.Main in 'Interfaces\ViewModels\Interfaces.ViewModel.Main.pas',
  Interfaces.ViewModel.Sale in 'Interfaces\ViewModels\Interfaces.ViewModel.Sale.pas',
  Interfaces.ViewModel.Reversal in 'Interfaces\ViewModels\Interfaces.ViewModel.Reversal.pas',
  Interfaces.ViewModel.CashInOut in 'Interfaces\ViewModels\Interfaces.ViewModel.CashInOut.pas',
  Interfaces.ViewModel.Reports in 'Interfaces\ViewModels\Interfaces.ViewModel.Reports.pas',
  Interfaces.ViewModel.Login in 'Interfaces\ViewModels\Interfaces.ViewModel.Login.pas',
  Interfaces.ViewModel.SelectItem in 'Interfaces\ViewModels\Interfaces.ViewModel.SelectItem.pas',
  Interfaces.ViewModel.SelectClient in 'Interfaces\ViewModels\Interfaces.ViewModel.SelectClient.pas',
  Interfaces.ViewModel.CheckItem in 'Interfaces\ViewModels\Interfaces.ViewModel.CheckItem.pas',
  Interfaces.ViewModel.SelectSale in 'Interfaces\ViewModels\Interfaces.ViewModel.SelectSale.pas',
  Interfaces.View.Main in 'Interfaces\Views\Interfaces.View.Main.pas',
  DataModule.Items in 'DataModules\DataModule.Items.pas' {DataModuleItems: TDataModule},
  DataModule.Clients in 'DataModules\DataModule.Clients.pas' {DataModuleClients: TDataModule},
  DataModule.Sale in 'DataModules\DataModule.Sale.pas' {DataModuleSale: TDataModule},
  Globals in 'Globals.pas',
  Helper.MyFuncs in 'Helpers\Helper.MyFuncs.pas',
  Device.FP700X in 'Device.FP700X.pas' {DeviceFP700X},
  Model_FP700X in 'Model_FP700X.pas',
  Model.Pattern.Observer.Observer in '..\Common\Models\Model.Pattern.Observer.Observer.pas',
  Model.Pattern.Observer.Observable in '..\Common\Models\Model.Pattern.Observer.Observable.pas',
  Model.Notification in '..\Common\Models\Model.Notification.pas',
  Model.AppSettings in 'Models\Model.AppSettings.pas',
  Model.Generator.GIDs in 'Models\Model.Generator.GIDs.pas',
  Model.Classes.Client in 'Models\Model.Classes.Client.pas',
  Model.Classes.Sales in 'Models\Model.Classes.Sales.pas',
  Model.Classes.Sale in 'Models\Model.Classes.Sale.pas',
  Model.Classes.Sale.Details in 'Models\Model.Classes.Sale.Details.pas',
  Model.Classes.Sale.Detail in 'Models\Model.Classes.Sale.Detail.pas',
  Model.Classes.Sale.Cancellations in 'Models\Model.Classes.Sale.Cancellations.pas',
  Model.Classes.Sale.Cancellation in 'Models\Model.Classes.Sale.Cancellation.pas',
  Model.Classes.Sale.Payments in 'Models\Model.Classes.Sale.Payments.pas',
  Model.Classes.Sale.Payment in 'Models\Model.Classes.Sale.Payment.pas',
  Model.Main in 'Models\Model.Main.pas',
  Model.Sale in 'Models\Model.Sale.pas',
  Model.Reversal in 'Models\Model.Reversal.pas',
  Model.CashInOut in 'Models\Model.CashInOut.pas',
  Model.Reports in 'Models\Model.Reports.pas',
  Model.Login in 'Models\Model.Login.pas',
  Model.SelectItem in 'Models\Model.SelectItem.pas',
  Model.SelectClient in 'Models\Model.SelectClient.pas',
  Model.CheckItem in 'Models\Model.CheckItem.pas',
  Model.SelectSale in 'Models\Model.SelectSale.pas',
  ViewModel.Main in 'ViewModels\ViewModel.Main.pas',
  ViewModel.Sale in 'ViewModels\ViewModel.Sale.pas',
  ViewModel.Reversal in 'ViewModels\ViewModel.Reversal.pas',
  ViewModel.CashInOut in 'ViewModels\ViewModel.CashInOut.pas',
  ViewModel.Reports in 'ViewModels\ViewModel.Reports.pas',
  ViewModel.Login in 'ViewModels\ViewModel.Login.pas',
  ViewModel.SelectItem in 'ViewModels\ViewModel.SelectItem.pas',
  ViewModel.SelectClient in 'ViewModels\ViewModel.SelectClient.pas',
  ViewModel.CheckItem in 'ViewModels\ViewModel.CheckItem.pas',
  ViewModel.SelectSale in 'ViewModels\ViewModel.SelectSale.pas',
  View.Message in 'Views\View.Message.pas' {ViewMessage},
  View.Sale in 'Views\View.Sale.pas' {ViewSale},
  View.Reversal in 'Views\View.Reversal.pas' {ViewReversal},
  View.CashInOut in 'Views\View.CashInOut.pas' {ViewCashInOut},
  View.Reports in 'Views\View.Reports.pas' {ViewReports},
  View.Login in 'Views\View.Login.pas' {ViewLogin},
  View.SelectItem in 'Views\View.SelectItem.pas' {ViewSelectItem},
  View.SelectClient in 'Views\View.SelectClient.pas' {ViewSelectClient},
  View.CheckItem in 'Views\View.CheckItem.pas' {ViewCheckItem},
  View.SelectSale in 'Views\View.SelectSale.pas' {ViewSelectSale},
  View.Main in 'Views\View.Main.pas' {ViewMain},
  ButtonWithColor in 'Components\ButtonWithColor.pas',
  View.CashIn in 'Views\View.CashIn.pas' {ViewCashIn},
  Interfaces.ViewModel.CashIn in 'Interfaces\ViewModels\Interfaces.ViewModel.CashIn.pas',
  ViewModel.CashIn in 'ViewModels\ViewModel.CashIn.pas',
  Interfaces.Model.CashIn in 'Interfaces\Models\Interfaces.Model.CashIn.pas',
  Model.CashIn in 'Models\Model.CashIn.pas',
  View.CashOut in 'Views\View.CashOut.pas' {ViewCashOut},
  Interfaces.ViewModel.CashOut in 'Interfaces\ViewModels\Interfaces.ViewModel.CashOut.pas',
  ViewModel.CashOut in 'ViewModels\ViewModel.CashOut.pas',
  Interfaces.Model.CashOut in 'Interfaces\Models\Interfaces.Model.CashOut.pas',
  Model.CashOut in 'Models\Model.CashOut.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TDataModuleItems, DataModuleItems);
  Application.CreateForm(TDataModuleClients, DataModuleClients);
  Application.CreateForm(TDataModuleSale, DataModuleSale);
  Application.CreateForm(TViewMain, ViewMain);
  Application.CreateForm(TViewMessage, ViewMessage);
  Application.CreateForm(TDeviceFP700X, DeviceFP700X);
  Application.Run;
end.
