object ViewNomenclaturePaymentType: TViewNomenclaturePaymentType
  Left = 0
  Top = 0
  BorderIcons = []
  Caption = #1042#1048#1044' '#1055#1051#1040#1065#1040#1053#1045
  ClientHeight = 114
  ClientWidth = 594
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -16
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Position = poOwnerFormCenter
  Visible = True
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 19
  object LabelName: TLabel
    AlignWithMargins = True
    Left = 4
    Top = 8
    Width = 586
    Height = 19
    Margins.Left = 4
    Margins.Top = 8
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alTop
    Caption = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077':'
    ExplicitWidth = 112
  end
  object Panel: TPanel
    AlignWithMargins = True
    Left = 4
    Top = 70
    Width = 586
    Height = 40
    Margins.Left = 4
    Margins.Top = 0
    Margins.Right = 4
    Margins.Bottom = 4
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 0
    object ButtonConfirm: TButton
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 166
      Height = 32
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alLeft
      Caption = #1047#1072#1087#1080#1089
      TabOrder = 0
      OnClick = ButtonConfirmClick
    end
    object ButtonCancel: TButton
      AlignWithMargins = True
      Left = 416
      Top = 4
      Width = 166
      Height = 32
      Margins.Left = 4
      Margins.Top = 4
      Margins.Right = 4
      Margins.Bottom = 4
      Align = alRight
      Caption = #1054#1090#1082#1072#1079
      TabOrder = 1
      OnClick = ButtonCancelClick
    end
  end
  object DBEditName: TDBEdit
    AlignWithMargins = True
    Left = 4
    Top = 35
    Width = 586
    Height = 27
    Margins.Left = 4
    Margins.Top = 4
    Margins.Right = 4
    Margins.Bottom = 8
    Align = alTop
    DataField = 'Name'
    DataSource = DataModulePaymentTypes.DataSource
    TabOrder = 1
  end
end
